### PR TITLE
Remove <distributionManagement/> section from pom.xml

### PR DESCRIPTION
**Pull request by scoheb**
We inherit it from plugin pom

### CODE REVIEW

**Comment by olivergondza** [comment]
Removing `repositories` and/or `pluginRepositories` can be a problem as that is where the parent pom resided. Chicken vs. egg.

**Comment by scoheb** [comment]
So your recommendation is to keep it as-is?

**Comment by pjanouse** [comment]
@scoheb 
Try 'mvn clean package -Dmaven.repo.local=local-repo' and you should see what is necessary.

My result with PR#32 included:

> mvn clean package -Dmaven.repo.local=local-repo
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/jenkins-ci/plugins/plugin/2.12/plugin-2.12.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:foreman-node-sharing:1.2.1-SNAPSHOT (/home/pjanouse/devel/git/foreman-node-sharing-plugin-pjanouse/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.jenkins-ci.plugins:plugin:pom:2.12 in central (http://repo.maven.apache.org/maven2) and 'parent.relativePath' points at no local POM @ line 5, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by scoheb** [comment]
I guess it depends on what is in your settings.xml. With this PR, I am able to run the command you specified.

I followed https://wiki.jenkins-ci.org/display/JENKINS/Plugin+tutorial#Plugintutorial-SettingUpEnvironment for my settings.xml.

**Comment by pjanouse** [comment]
You are certainly right, however I've never needed to touch my settings.xml for work related to Jenkins or its plug-in(s). 

So I guess it is a common practice to have that definition in pom.xml for every plug-in etc. (at least in which I've worked already)

**Comment by scoheb** [comment]
...it is not a big deal. let's keep it in the pom.xml. I will close this.

**Pull request closed without merging**
