### PR TITLE
[JENKINS-42053] Usage of IP attribute from Foreman removed from the core

### PR DESCRIPTION
**Pull request by pjanouse**

### CODE REVIEW

**Comment by scoheb** [comment]
Fine by me...but this would have left the possibility of someone using IP in the case where DNS might not have been configured correctly. This can be the case in many labs sometimes, no?

**Comment by pjanouse** [comment]
@olivergondza 
Yes, you are right; this attribute/value corresponds with "Name" in Foreman.

**Comment by pjanouse** [comment]
@scoheb 
Well, you are right too... so what about this slight modification - I can imagine to do an attempt to resolve `reservedHostName` in the code (at the same place where I removed current code), when exception occurred (like 'host not found'), try to get the `IP` attribute and if received, use it instead of `reservedHostName`? When resolving successes just use `reservedHostName`...

**Comment by pjanouse** [comment]
The only issue I can see...Foreman supports to have more interfaces (that means more IPs) attached to one host... how we should handle this situation?

**Comment by olivergondza** [comment]
How about using the IP as the name/hostname in case it can not be reliable resolved by all Jenkinses? One of the use-cases can be using FIP of openstack machine.

**Comment by pjanouse** [comment]
Oliver, your use case is covered already.

If we go by my suggestion from yesterday, when IP address is as a hostname, resolving passes too (IP address will be the same as the hostname) so we don't need the `IP` attribute in this case. I was thinking about the `IP` only when the resolving mechanism fails.

**Comment by olivergondza** [comment]
> I was thinking about the IP only when the resolving mechanism fails.

I do not think this is something we have to worry about. Not until we see that problem at least.

**Comment by pjanouse** [comment]
Put an IP instead of hostname works as expected - verified so this use-case is covered correctly. In addition the tested node didn't have defined Network Interface... so it is the case we want to solve.

So I think currently state of this PR is exactly what we want now.

**Pull request merged**
